### PR TITLE
Generate book in epub format

### PR DESCRIPTION
**Pull request by priithaamer**
Hey, i added rake task to generate Git book in epub format. Preview is available here: http://f.priithaamer.com/gitbook/gitbook.epub

Cheers,
Priit.

### CODE REVIEW

**Comment by ciampix** [comment]
I tested the epub doc converted to mobi via calibre onto my Kindle. It worked perfectly. Why this pull request is hanging from so much time? It is really useful!

**Comment by ciampix** [comment]
Reading the generated epub I have noticed that the "<" and ">" symbols are not converted correctly. They appear respectively as & l t ; or & g t ; as an HTML code unconverted...

**Comment by dharFr** [comment]
Agree with @ciampix 
The doc in ePub format is really great. IMO, this request should be merged,

Anyway, thanks @priithaamer

Regards.

**Comment by ghost** [comment]
The images do not resize to fix to some reader devices.

**Comment by Irio** [comment]
My Kindle thanks.

**Pull request closed without merging**
